import { useState, useRef, useEffect } from 'react';
import AIAgentsNav from './AIAgentsNav';
import AIAgentsKPICard from './AIAgentsKPICard';
import ArticleInsights from './ArticleInsights';
import KnowledgeGaps from './KnowledgeGaps';
import ProfileMenu from '../ProfileMenu';
import { ChevronDownIcon, CheckIcon, SearchIcon, BellIcon, AIAgentsLogoIcon, SparkleIcon } from '../Icons';
import './AIAgentsPage.css';

const conversationsData = {
  title: 'Conversations',
  description: 'Understand what percentage of conversations included responses generated by UltimateGPT, compared to Intent only conversations created in the Dialogue Builder',
  value: '12.766',
  trend: 'down',
  trendValue: '2.4%',
  bars: [
    { name: 'UltimateGPT Conversations', percentage: 80.6, count: '12345', color: 'blue' },
    { name: 'Intent Predicted Conversations', percentage: 56.2, count: '435', color: 'green' },
  ]
};

const ugptAnswersData = {
  title: 'UGPT Answers',
  description: 'See how visitor messages align with the content available in your knowledge sources, and therefore we successfully generated a response.',
  value: '1.456',
  trend: 'up',
  trendValue: '7.1%',
  bars: [
    { name: 'Response Generated', percentage: 80.6, count: '12345', color: 'blue' },
    { name: 'Not Understood', percentage: 20.4, count: '654', color: 'red' },
  ]
};

const dropdownOptions = {
  language: ['Coca Cola', 'English', 'Spanish', 'French'],
  labels: ['Advocacy French', 'Support', 'Sales', 'Marketing'],
  advanced: ['Advocacy French', 'All Users', 'New Users'],
  timeFrame: ['Last 7 days', 'Last 30 days', 'Last 90 days', 'Custom'],
};

function NavHeader({ onProductChange, selectedProduct, products = [], isCollapsed }) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef(null);

  useEffect(() => {
    function handleClickOutside(event) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    }

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }
  }, [isOpen]);

  const handleProductSelect = (product) => {
    if (onProductChange) {
      onProductChange(product);
    }
    setIsOpen(false);
  };

  return (
    <div className={`ai-agents-nav-header ${isCollapsed ? 'ai-agents-nav-header--collapsed' : ''}`} ref={dropdownRef}>
      <div className="ai-agents-nav-header__logo">
        <AIAgentsLogoIcon className="ai-agents-nav-header__logo-icon" />
      </div>
      {!isCollapsed && (
        <>
          <button 
            className={`ai-agents-nav-header__product-selector ${isOpen ? 'active' : ''}`}
            onClick={() => setIsOpen(!isOpen)}
          >
            <span className="ai-agents-nav-header__product-name">{selectedProduct?.name || 'AI agents'}</span>
            <ChevronDownIcon className={`ai-agents-nav-header__chevron ${isOpen ? 'rotated' : ''}`} />
          </button>
          
          {isOpen && products.length > 0 && (
            <div className="ai-agents-nav-header__dropdown">
              <div className="ai-agents-nav-header__dropdown-list">
                {products.map((product) => {
                  const Icon = product.icon;
                  const isSelected = selectedProduct?.id === product.id;
                  return (
                    <button
                      key={product.id}
                      className={`ai-agents-nav-header__dropdown-item ${isSelected ? 'selected' : ''}`}
                      onClick={() => handleProductSelect(product)}
                    >
                      <Icon className="ai-agents-nav-header__dropdown-icon" />
                      <span className="ai-agents-nav-header__dropdown-name">{product.name}</span>
                      {isSelected && <CheckIcon className="ai-agents-nav-header__dropdown-check" />}
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

function ContentHeader({ onOpenCommandPalette }) {
  return (
    <div className="ai-agents-content-header">
      <div className="ai-agents-content-header__left">
        <button className="ai-agents-content-header__bot-selector">
          <SparkleIcon className="ai-agents-content-header__bot-icon" />
          <span>Test Bot</span>
          <ChevronDownIcon className="ai-agents-content-header__chevron" />
        </button>
      </div>
      
      <button 
        className="ai-agents-content-header__search"
        onClick={onOpenCommandPalette}
        type="button"
      >
        <SearchIcon className="ai-agents-content-header__search-icon" />
        <span className="ai-agents-content-header__search-text">Search for apps and commands or ask AI...</span>
        <span className="ai-agents-content-header__search-shortcut">⌘ + K</span>
      </button>
      
      <div className="ai-agents-content-header__right">
        <button className="ai-agents-content-header__icon-btn" title="Settings">
          <span className="material-symbols-rounded">settings</span>
        </button>
        <button className="ai-agents-content-header__icon-btn" title="Apps">
          <span className="material-symbols-rounded">apps</span>
        </button>
        <ProfileMenu />
      </div>
    </div>
  );
}

function FilterDropdown({ label, value, options, onChange }) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef(null);

  useEffect(() => {
    function handleClickOutside(event) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    }

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }
  }, [isOpen]);

  return (
    <div className="ai-agents-filter" ref={dropdownRef}>
      <label className="ai-agents-filter__label">{label}</label>
      <button 
        className={`ai-agents-filter__select ${isOpen ? 'active' : ''}`}
        onClick={() => setIsOpen(!isOpen)}
      >
        <span className="ai-agents-filter__value">{value}</span>
        <ChevronDownIcon className={`ai-agents-filter__chevron ${isOpen ? 'rotated' : ''}`} />
      </button>
      
      {isOpen && (
        <div className="ai-agents-filter__dropdown">
          {options.map((option, index) => (
            <button
              key={index}
              className={`ai-agents-filter__option ${option === value ? 'selected' : ''}`}
              onClick={() => {
                onChange(option);
                setIsOpen(false);
              }}
            >
              {option}
              {option === value && <CheckIcon className="ai-agents-filter__check" />}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

export default function AIAgentsPage({ onProductChange, selectedProduct, products, onOpenCommandPalette }) {
  const [filters, setFilters] = useState({
    language: 'Coca Cola',
    labels: 'Advocacy French',
    advanced: 'Advocacy French',
    timeFrame: 'Last 7 days',
  });
  const [isNavCollapsed, setIsNavCollapsed] = useState(false);

  const handleFilterChange = (key, value) => {
    setFilters(prev => ({ ...prev, [key]: value }));
  };

  return (
    <div className="ai-agents-page">
      <div className="ai-agents-page__body">
        {/* Navigation Column */}
        <div className={`ai-agents-page__nav-column ${isNavCollapsed ? 'ai-agents-page__nav-column--collapsed' : ''}`}>
          <NavHeader 
            onProductChange={onProductChange} 
            selectedProduct={selectedProduct} 
            products={products}
            isCollapsed={isNavCollapsed}
          />
          <AIAgentsNav 
            isCollapsed={isNavCollapsed} 
            onToggleCollapse={() => setIsNavCollapsed(!isNavCollapsed)} 
          />
        </div>
        
        {/* Content Column */}
        <div className="ai-agents-page__content-column">
          <ContentHeader onOpenCommandPalette={onOpenCommandPalette} />
          
          <main className="ai-agents-page__main">
            <div className="ai-agents-page__content">
              <div className="ai-agents-page__header">
                <h1 className="ai-agents-page__title">UGPT Performance</h1>
                <p className="ai-agents-page__subtitle">Last updated 2 hours ago</p>
              </div>
              
              <div className="ai-agents-page__filters">
                <FilterDropdown 
                  label="Language" 
                  value={filters.language} 
                  options={dropdownOptions.language}
                  onChange={(v) => handleFilterChange('language', v)}
                />
                <FilterDropdown 
                  label="Labels" 
                  value={filters.labels} 
                  options={dropdownOptions.labels}
                  onChange={(v) => handleFilterChange('labels', v)}
                />
                <FilterDropdown 
                  label="Advanced" 
                  value={filters.advanced} 
                  options={dropdownOptions.advanced}
                  onChange={(v) => handleFilterChange('advanced', v)}
                />
                <FilterDropdown 
                  label="Time Frame" 
                  value={filters.timeFrame} 
                  options={dropdownOptions.timeFrame}
                  onChange={(v) => handleFilterChange('timeFrame', v)}
                />
              </div>
              
              <div className="ai-agents-page__kpis">
                <AIAgentsKPICard {...conversationsData} />
                <AIAgentsKPICard {...ugptAnswersData} />
              </div>
              
              <ArticleInsights />
              
              <KnowledgeGaps />
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}

